---

name: CI

on:
  pull_request:
    branches: [devel]

  push:
    branches: [devel]

jobs:
  pull_request:
    runs-on: ubuntu-20.04
    name: pull_request
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run
        run: |
          tox -e ansible-builder
