---

name: CI

on:
  pull_request:
    branches: [devel]

  push:
    branches: [devel]

jobs:
  podman:
    runs-on: ubuntu-20.04
    name: Podman
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run
        run: |
          tox -e podman

  docker:
    runs-on: ubuntu-20.04
    name: Docker
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run
        run: |
          tox -e docker

  check_diff:
    runs-on: ubuntu-20.04
    name: Check diff
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Run
        run: |
          tox -e check-diff
