name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-20.04
    name: Release
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox

      - name: Build image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          # tox -e docker -- --tag=quay.io/shanemcd/awx-ee:${{ github.event.release.tag_name }}
          docker pull quay.io/shanemcd/awx-ee
          docker tag quay.io/shanemcd/awx-ee quay.io/shanemcd/awx-ee:${{ github.event.release.tag_name }}

      - name: Push To Quay
        uses: redhat-actions/push-to-registry@v2.1.1
        with:
          image: quay.io/shanemcd/awx-ee
          tags: ${{ github.event.release.tag_name }}
          registry: quay.io/shanemcd/
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
